# Use the official Nginx image as the base image
FROM nginx:latest

# Copy custom Nginx configuration file
COPY nginx.conf /etc/nginx/nginx.conf

# Copy static files (e.g., HTML, CSS, JavaScript) to the appropriate directory
# COPY static /usr/share/nginx/html

# Expose port 80 to allow external access
EXPOSE 80

# Start Nginx when the container starts
# CMD ["nginx", "-g", "daemon off;"]