# Generated by Django 4.0.6 on 2022-07-16 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='stocks',
            field=models.CharField(max_length=4),
        ),
    ]
